spring:
  application:
    name: GhanaVACTours

  datasource:
    url: jdbc:postgresql://localhost:5438/ghana_vac_tours
    driver-class-name: org.postgresql.Driver
    username: ghana_vac
    password: ghana_vac_pass

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
    port: 8080
