CREATE TABLE address
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street  VARCHAR(50)                             NOT NULL,
    city    VARCHAR(50)                             NOT NULL,
    state   VARCHAR(2)                              NOT NULL,
    zip     VARCHAR(5)                              NOT NULL,
    country VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE booking
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_date      date                                    NOT NULL,
    travel_start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status            VARCHAR(50)                             NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    itinerary_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE destination
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(150)                            NOT NULL,
    region VARCHAR(100),
    CONSTRAINT pk_destination PRIMARY KEY (id)
);

CREATE TABLE itinerary
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(150)                            NOT NULL,
    duration_days BIGINT                                  NOT NULL,
    CONSTRAINT pk_itinerary PRIMARY KEY (id)
);

CREATE TABLE itinerary_destination
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_number     BIGINT,
    itinerary_id   BIGINT                                  NOT NULL,
    destination_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_itinerary_destination PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fname        VARCHAR(50)                             NOT NULL,
    lname        VARCHAR(50),
    email        VARCHAR(100)                            NOT NULL,
    phone_number VARCHAR(20)                             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    address_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_address UNIQUE (address_id);

ALTER TABLE itinerary_destination
    ADD CONSTRAINT FK_DESTINATION FOREIGN KEY (destination_id) REFERENCES destination (id);

ALTER TABLE itinerary_destination
    ADD CONSTRAINT FK_ITINERARY FOREIGN KEY (itinerary_id) REFERENCES itinerary (id);

ALTER TABLE booking
    ADD CONSTRAINT FK_ITINERARY_BOOKING FOREIGN KEY (itinerary_id) REFERENCES itinerary (id) ON DELETE CASCADE;

ALTER TABLE booking
    ADD CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE;

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);